version: '3.1'

services:
  db:
    image: postgres
    #restart: always
    ports:
      - 5432:5432
    # command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: postgres
