name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13.3-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.14.0' # Define the elixir version [required]
        otp-version: '24.3.4.2' # Define the OTP version [required]

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Check unused dependencies
      run: mix deps.unlock --check-unused

    - name: Check formatting
      run: mix format --check-formatted

    - name: Compile code
      run: mix compile --warnings-as-errors --all-warnings

    - name: Create database
      run: mix ecto.create

    - name: Run migrations
      run: mix ecto.migrate

    - name: Credo
      run: mix credo --strict

    - name: Run tests
      run: mix coveralls --warnings-as-errors

